enhavo_redirect_admin_redirect_index:
    path: /redirect/index
    defaults:
        _expose: admin
        _vue:
            component: resource-index
            groups: admin
            meta:
                api: enhavo_redirect_admin_api_redirect_index
        _endpoint:
            type: admin

enhavo_redirect_admin_redirect_create:
    path: /redirect/create
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_redirect_admin_api_redirect_create
        _endpoint:
            type: admin

enhavo_redirect_admin_redirect_update:
    path: '/redirect/update/{id}'
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_redirect_admin_api_redirect_update
        _endpoint:
            type: admin
